alpha = 1.0
disabledAlpha = 0.6000000238418579
windowPadding = [8.0, 8.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 0.0
frameBorderSize = 1.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 0.0
grabMinSize = 10.0
grabRounding = 0.0
tabRounding = 0.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(127, 127, 127, 1.0)"
WindowBg = "rgba(73, 86, 66, 1.0)"
ChildBg = "rgba(73, 86, 66, 1.0)"
PopupBg = "rgba(61, 68, 51, 1.0)"
Border = "rgba(137, 145, 130, 0.5)"
BorderShadow = "rgba(35, 40, 28, 0.5199999809265137)"
FrameBg = "rgba(61, 68, 51, 1.0)"
FrameBgHovered = "rgba(68, 76, 58, 1.0)"
FrameBgActive = "rgba(76, 86, 66, 1.0)"
TitleBg = "rgba(61, 68, 51, 1.0)"
TitleBgActive = "rgba(73, 86, 66, 1.0)"
TitleBgCollapsed = "rgba(0, 0, 0, 0.5099999904632568)"
MenuBarBg = "rgba(61, 68, 51, 1.0)"
ScrollbarBg = "rgba(89, 107, 79, 1.0)"
ScrollbarGrab = "rgba(71, 81, 61, 1.0)"
ScrollbarGrabHovered = "rgba(63, 76, 56, 1.0)"
ScrollbarGrabActive = "rgba(58, 68, 53, 1.0)"
CheckMark = "rgba(150, 137, 45, 1.0)"
SliderGrab = "rgba(89, 107, 79, 1.0)"
SliderGrabActive = "rgba(137, 145, 130, 0.5)"
Button = "rgba(73, 86, 66, 0.4000000059604645)"
ButtonHovered = "rgba(89, 107, 79, 1.0)"
ButtonActive = "rgba(137, 145, 130, 0.5)"
Header = "rgba(89, 107, 79, 1.0)"
HeaderHovered = "rgba(89, 107, 79, 0.6000000238418579)"
HeaderActive = "rgba(137, 145, 130, 0.5)"
Separator = "rgba(35, 40, 28, 1.0)"
SeparatorHovered = "rgba(137, 145, 130, 1.0)"
SeparatorActive = "rgba(150, 137, 45, 1.0)"
ResizeGrip = "rgba(48, 58, 45, 0.0)"
ResizeGripHovered = "rgba(137, 145, 130, 1.0)"
ResizeGripActive = "rgba(150, 137, 45, 1.0)"
Tab = "rgba(89, 107, 79, 1.0)"
TabHovered = "rgba(137, 145, 130, 0.7799999713897705)"
TabActive = "rgba(150, 137, 45, 1.0)"
TabUnfocused = "rgba(61, 68, 51, 1.0)"
TabUnfocusedActive = "rgba(89, 107, 79, 1.0)"
PlotLines = "rgba(155, 155, 155, 1.0)"
PlotLinesHovered = "rgba(150, 137, 45, 1.0)"
PlotHistogram = "rgba(255, 198, 71, 1.0)"
PlotHistogramHovered = "rgba(255, 153, 0, 1.0)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.05999999865889549)"
TextSelectedBg = "rgba(150, 137, 45, 1.0)"
DragDropTarget = "rgba(186, 170, 61, 1.0)"
NavHighlight = "rgba(150, 137, 45, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.699999988079071)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2000000029802322)"
ModalWindowDimBg = "rgba(204, 204, 204, 0.3499999940395355)"